/**
 * Static site generation: renders every route of the app to HTML so that
 * visitors, search engines, AI crawlers and link previews get real content
 * without running JavaScript. The browser then hydrates the same markup.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const DIST = 'dist';

interface ServerEntry {
  getRoutes: () => string[];
  render: (url: string) => Promise<{ html: string; head: string; lang: string; status: number }>;
  buildSitemap: (routes: string[]) => string;
  buildLlmsTxt: () => string;
}

/** '/' → index.html, '/en' → en.html, '/en/cv' → en/cv.html (clean URLs on Netlify). */
const fileFor = (route: string) => (route === '/' ? 'index.html' : `${route.slice(1)}.html`);

export const prerender = async () => {
  const template = await readFile(join(DIST, 'index.html'), 'utf8');
  const entry = (await import(pathToFileURL(join(process.cwd(), '.ssr', 'entry-server.js')).href)) as ServerEntry;

  // Preload the main font (hashed file name from the client build)
  const assets = await readdir(join(DIST, 'assets'));
  const font = assets.find((f) => /^archivo-latin-wdth-normal-.*\.woff2$/.test(f));
  const preload = font
    ? `<link rel="preload" href="/assets/${font}" as="font" type="font/woff2" crossorigin />`
    : '';

  const page = (html: string, head: string, lang: string, dataPath: string) =>
    template
      .replace('<html lang="fr">', `<html lang="${lang}">`)
      .replace('<!--app-preload-->', preload)
      .replace('<!--app-head-->', head)
      .replace('<div id="root"><!--app-html--></div>', `<div id="root" data-path="${dataPath}">${html}</div>`);

  const routes = entry.getRoutes();
  const rewrites: string[] = [];
  for (const route of routes) {
    const { html, head, lang, status } = await entry.render(route);
    if (status !== 200) throw new Error(`Route ${route} rendered as ${status}`);
    const file = fileFor(route);
    await mkdir(dirname(join(DIST, file)), { recursive: true });
    await writeFile(join(DIST, file), page(html, head, lang, route));
    if (route !== '/') rewrites.push(`${route}  /${file}  200`);
  }

  // 404 page: served by Netlify with a real 404 status for unknown URLs
  const notFound = await entry.render('/__not-found__');
  await writeFile(join(DIST, '404.html'), page(notFound.html, notFound.head, notFound.lang, '/__not-found__'));

  await writeFile(join(DIST, 'sitemap.xml'), entry.buildSitemap(routes));
  await writeFile(join(DIST, 'llms.txt'), entry.buildLlmsTxt());

  // Explicit rewrites make clean URLs independent of Netlify's pretty-URL setting.
  // (/cv and /card keep the same addresses as on the previous site.)
  const redirects = ['# Generated by scripts/prerender.ts', ...rewrites];
  await writeFile(join(DIST, '_redirects'), `${redirects.join('\n')}\n`);

  console.log(`  ${routes.length} routes + 404.html, sitemap.xml, llms.txt, _redirects`);
};
