import { useState } from 'react';
import { profile } from '../../data';
import { useL } from '../../i18n';
import { cn } from '../../lib/cn';

const WIDTHS = [480, 800, 1200];

interface PortraitProps {
  className?: string;
  imgClassName?: string;
  /** CSS sizes attribute, e.g. "(min-width: 1024px) 33vw, 100vw". */
  sizes?: string;
  priority?: boolean;
}

/**
 * Responsive portrait: AVIF → WebP → JPEG, generated by scripts/optimize-images.mjs.
 * Falls back to the original photo, then to a neutral placeholder if both fail.
 */
export const Portrait = ({ className, imgClassName, sizes = '(min-width: 1024px) 40vw, 100vw', priority }: PortraitProps) => {
  const l = useL();
  const [failed, setFailed] = useState(false);
  const { base, width, height, fallback } = profile.portrait;
  const srcSet = (ext: string) => WIDTHS.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ');

  if (failed) {
    return (
      <div
        role="img"
        aria-label={l(profile.portrait.alt)}
        className={cn('flex items-center justify-center bg-bg-2 font-semiwide text-display-m text-ink-3', className)}
        style={{ aspectRatio: `${width} / ${height}` }}
      >
        {profile.initials}
      </div>
    );
  }

  return (
    <picture className={className}>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        src={`${base}-800.jpg`}
        srcSet={srcSet('jpg')}
        sizes={sizes}
        width={width}
        height={height}
        alt={l(profile.portrait.alt)}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        fetchPriority={priority ? 'high' : 'auto'}
        onError={(e) => {
          const img = e.currentTarget;
          if (!img.src.endsWith(fallback)) {
            img.parentElement?.querySelectorAll('source').forEach((s) => s.remove());
            img.srcset = '';
            img.src = fallback;
          } else {
            setFailed(true);
          }
        }}
        className={cn('h-full w-full object-cover', imgClassName)}
      />
    </picture>
  );
};
